packages:
  # - packages/*
  - packages/shared
  - packages/support
  - packages/core
  - packages/filesystem
  - packages/database
  - packages/http
  - packages/cache
  - packages/config
  - packages/queue
  - packages/mail
  - packages/router
  - packages/console
  - packages/view
  - examples/*
  - docs

onlyBuiltDependencies:
  - esbuild

shamefullyHoist: true
