packages:
  - packages/shared
  - packages/support
  - packages/core
  - packages/filesystem
  - packages/database
  - packages/http
  - packages/cache
  - packages/config
  - packages/hashing
  - packages/queue
  - packages/mail
  - packages/router
  - packages/console
  - packages/view
  - packages/url
  - examples/*
  - docs

catalog:
  '@changesets/cli': ^2.29.7
  '@eslint/js': ^9.39.1
  '@rollup/plugin-run': ^3.1.0
  '@swc/core': ^1.15.0
  '@types/luxon': ^3.7.1
  '@types/nodemailer': ^6.4.17
  '@types/semver': ^7.7.1
  '@typescript-eslint/eslint-plugin': ^8.46.3
  '@typescript-eslint/parser': ^8.46.3
  '@vitest/coverage-v8': ^3.2.4
  argon2: ^0.44.0
  barrelize: 1.6.6
  barrelsby: ^2.8.1
  bcryptjs: ^3.0.2
  cross-env: ^10.1.0
  dayjs: ^1.11.18
  detect-port: ^2.1.0
  dotenv: ^17.2.3
  dotenv-expand: ^12.0.3
  edge.js: ^6.3.0
  escalade: ^3.2.0
  eslint: ^9.39.1
  execa: ^9.6.0
  fast-glob: ^3.3.3
  husky: ^9.1.7
  knex: ^3.1.0
  luxon: ^3.7.2
  path: ^0.12.7
  preferred-pm: ^4.1.1
  reflect-metadata: ^0.2.2
  resolve-from: ^5.0.0
  rimraf: ^6.1.0
  semver: ^7.7.2
  source-map-support: ^0.5.21
  sqlite3: 5.1.7
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tslib: ^2.8.1
  tsx: ^4.20.6
  typescript-eslint: ^8.46.3
  utility-types: ^3.11.0
  vite-tsconfig-paths: ^5.1.4

catalogs:
  prod:
    '@h3ravel/arquebus': ^0.6.13
    '@h3ravel/musket': ^0.3.9
    h3: 2.0.1-rc.5

ignoredBuiltDependencies:
  - '@h3ravel/arquebus'
  - '@swc/core'
  - argon2

onlyBuiltDependencies:
  - esbuild
  - sqlite3
  - '@h3ravel/musket'

shamefullyHoist: true
