packages:
  - packages/shared
  - packages/support
  - packages/core
  - packages/filesystem
  - packages/database
  - packages/http
  - packages/cache
  - packages/config
  - packages/hashing
  - packages/queue
  - packages/mail
  - packages/router
  - packages/console
  - packages/view
  - packages/url
  - examples/*
  - docs

ignoredBuiltDependencies:
  - '@h3ravel/arquebus'
  - '@h3ravel/musket'
  - '@swc/core'
  - argon2
  - sqlite3

onlyBuiltDependencies:
  - esbuild

shamefullyHoist: true
